### ISSUE TITLE
We need to work faster xD

### ISSUE THREAD

**Issue by FishingHacks** [Rediverse/eztube#1]
Warum sind bisher fast alle commits von mir? 🤔

**Comment by RedCrafter07** [comment]
Weil ich heute keine Zeit habe und nicht am PC bin 😳

**Comment by FishingHacks** [comment]
we need to leave this open xD

**Comment by DavidCraftDev** [comment]
Ihr werdet damit sehr Erfolgreich werden, ich kenne so viele die sich über die YT API aufgeregt haben xD

**Comment by RedCrafter07** [comment]
^^
War deine Idee :)

**Comment by FishingHacks** [comment]
Und bisher größtenteils meine umsetzung

**Comment by RedCrafter07** [comment]
Und ich helfe bald auch mit :)

**Comment by FishingHacks** [comment]
:)
